### ISSUE TITLE
About Code of LAHDR

### ISSUE THREAD

**Issue by fonte-fs** [ARWhooo/LAHDR#1]
Dear professor,

Thanks for your great work.  
When could you provided related codes?  I'm interested in details of your EBNet.

**Comment by ARWhooo** [comment]
We are terribly sorry about the publishing delay for the codes. Due to series of issues and errands, we plan to publish the full codes at the end of August. Currently we are refactoring the Tensorflow 1.0 codes, and constructing its PyTorch version.

**Comment by caogaofeng** [comment]
waiting for code release
